spring:
  application:
    name: file
server:
  port: 9003
  servlet:
    context-path: /file

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
file:
  domain: http://127.0.0.1:9000/file/f/
  path: E:/springcloud/springcloud_vue/

