spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
        - id: business
#          uri: http://127.0.0.1:9002
          uri: lb://business
          predicates:
            - Path=/business/**

server:
  #路由最重要  所以最先开始
  port: 9000
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#路由转发
