spring:
  application:
    name: gateway
server:
  #路由最重要  所以最先开始
  port: 9000
#eureka:
#  client:
#    fetch-registry: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false