spring:
  application:
    name: system
server:
  port: 9001
  servlet:
    context-path: /system
#eureka:
#  client:
#    fetch-registry: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false